-- ============================================================
-- S.A. KIDDIES ACADEMY SRMS
-- ID CARD VERIFICATION SYSTEM
-- ============================================================
--
-- Supports QR verification for:
--   1. Students
--   2. Teachers
--
-- Teacher ID card details:
--   Name, employment type, form master, sex, phone, email
--
-- Student ID card details:
--   Name, admission number, class, photo
--
-- Session/term is NOT used on the physical ID cards.
-- ============================================================

-- ------------------------------------------------------------
-- Teacher details used by the ID card.
-- These fields are also exposed in the Admin > Teachers form.
-- ------------------------------------------------------------
ALTER TABLE public.teachers
  ADD COLUMN IF NOT EXISTS sex TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT;

-- ------------------------------------------------------------
-- Stable QR token registry
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.id_card_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    school_id BIGINT NOT NULL
        REFERENCES public.schools(id)
        ON DELETE CASCADE,

    entity_type TEXT NOT NULL
        CHECK (entity_type IN ('student', 'teacher')),

    entity_id BIGINT NOT NULL,

    token UUID NOT NULL
        DEFAULT gen_random_uuid(),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT id_card_tokens_entity_unique
        UNIQUE (entity_type, entity_id),

    CONSTRAINT id_card_tokens_token_unique
        UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS idx_id_card_tokens_token
    ON public.id_card_tokens(token);

CREATE INDEX IF NOT EXISTS idx_id_card_tokens_school_entity
    ON public.id_card_tokens(school_id, entity_type, entity_id);

ALTER TABLE public.id_card_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "id_card_tokens_admin_all"
ON public.id_card_tokens;

CREATE POLICY "id_card_tokens_admin_all"
ON public.id_card_tokens
FOR ALL
TO authenticated
USING (
    school_id IN (
        SELECT p.school_id
        FROM public.profiles p
        WHERE p.id = auth.uid()
          AND p.role = 'admin'
    )
)
WITH CHECK (
    school_id IN (
        SELECT p.school_id
        FROM public.profiles p
        WHERE p.id = auth.uid()
          AND p.role = 'admin'
    )
);

-- ------------------------------------------------------------
-- Admin-only token generator
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_or_create_id_card_token(
    p_entity_type TEXT,
    p_entity_id BIGINT
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_school_id BIGINT;
    v_token UUID;
BEGIN

    SELECT p.school_id
    INTO v_school_id
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.role = 'admin'
    LIMIT 1;

    IF v_school_id IS NULL THEN
        RAISE EXCEPTION
            'Only a school administrator can generate ID card tokens';
    END IF;

    IF p_entity_type = 'student' THEN

        IF NOT EXISTS (
            SELECT 1
            FROM public.students s
            WHERE s.id = p_entity_id
              AND s.school_id = v_school_id
        ) THEN
            RAISE EXCEPTION
                'Student not found in your school';
        END IF;

    ELSIF p_entity_type = 'teacher' THEN

        IF NOT EXISTS (
            SELECT 1
            FROM public.teachers t
            WHERE t.id = p_entity_id
              AND t.school_id = v_school_id
        ) THEN
            RAISE EXCEPTION
                'Teacher not found in your school';
        END IF;

    ELSE
        RAISE EXCEPTION
            'Invalid ID card entity type';
    END IF;

    SELECT ict.token
    INTO v_token
    FROM public.id_card_tokens ict
    WHERE ict.entity_type = p_entity_type
      AND ict.entity_id = p_entity_id
      AND ict.school_id = v_school_id
    LIMIT 1;

    IF v_token IS NOT NULL THEN
        RETURN v_token;
    END IF;

    INSERT INTO public.id_card_tokens (
        school_id,
        entity_type,
        entity_id
    )
    VALUES (
        v_school_id,
        p_entity_type,
        p_entity_id
    )
    RETURNING token INTO v_token;

    RETURN v_token;
END;
$$;

-- ------------------------------------------------------------
-- Replace the public verification function so teacher details
-- match the physical ID card.
-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS public.get_id_card_by_token(UUID);

CREATE FUNCTION public.get_id_card_by_token(
    p_token UUID
)
RETURNS TABLE (
    entity_type TEXT,
    entity_id BIGINT,

    school_name TEXT,
    school_address TEXT,
    school_phone TEXT,
    school_logo_url TEXT,

    name TEXT,
    identity_number TEXT,
    role_label TEXT,

    class_name TEXT,
    employment_type TEXT,
    form_master TEXT,
    sex TEXT,
    phone TEXT,
    email TEXT,

    photo_url TEXT,

    session_label TEXT,

    verified_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN

    RETURN QUERY

    SELECT
        ict.entity_type,
        ict.entity_id,

        sc.name::TEXT,
        sc.address::TEXT,
        sc.phone::TEXT,
        sc.logo_url::TEXT,

        CASE
            WHEN ict.entity_type = 'student'
                THEN st.name
            ELSE te.name
        END::TEXT,

        CASE
            WHEN ict.entity_type = 'student'
                THEN st.admission_no
            ELSE NULL
        END::TEXT,

        CASE
            WHEN ict.entity_type = 'student'
                THEN 'Student'
            ELSE 'Teacher'
        END::TEXT,

        CASE
            WHEN ict.entity_type = 'student'
                THEN student_class.name
            ELSE NULL
        END::TEXT,

        CASE
            WHEN ict.entity_type = 'teacher'
                THEN te.employment_type
            ELSE NULL
        END::TEXT,

        CASE
            WHEN ict.entity_type = 'teacher'
                THEN form_master_class.name
            ELSE NULL
        END::TEXT,

        CASE
            WHEN ict.entity_type = 'teacher'
                THEN te.sex
            ELSE NULL
        END::TEXT,

        CASE
            WHEN ict.entity_type = 'teacher'
                THEN te.phone
            ELSE NULL
        END::TEXT,

        CASE
            WHEN ict.entity_type = 'teacher'
                THEN te.email
            ELSE NULL
        END::TEXT,

        CASE
            WHEN ict.entity_type = 'student'
                THEN st.photo_url
            ELSE NULL
        END::TEXT,

        COALESCE(
            CASE
                WHEN sess.year_label IS NOT NULL
                    THEN sess.year_label || ' · ' || sess.term
                ELSE NULL
            END,
            'Current school record'
        )::TEXT,

        NOW()

    FROM public.id_card_tokens ict

    JOIN public.schools sc
        ON sc.id = ict.school_id

    LEFT JOIN public.students st
        ON ict.entity_type = 'student'
       AND st.id = ict.entity_id
       AND st.school_id = ict.school_id

    LEFT JOIN public.classes student_class
        ON student_class.id = st.class_id

    LEFT JOIN public.teachers te
        ON ict.entity_type = 'teacher'
       AND te.id = ict.entity_id
       AND te.school_id = ict.school_id

    LEFT JOIN public.classes form_master_class
        ON form_master_class.id = te.form_master_class_id

    LEFT JOIN LATERAL (
        SELECT
            a.year_label,
            a.term
        FROM public.academic_sessions a
        WHERE a.school_id = ict.school_id
          AND a.is_active = TRUE
        ORDER BY a.created_at DESC NULLS LAST
        LIMIT 1
    ) sess ON TRUE

    WHERE ict.token = p_token
      AND ict.is_active = TRUE
      AND (
            (
                ict.entity_type = 'student'
                AND st.id IS NOT NULL
            )
            OR
            (
                ict.entity_type = 'teacher'
                AND te.id IS NOT NULL
            )
          );
END;
$$;

GRANT EXECUTE
ON FUNCTION public.get_or_create_id_card_token(TEXT, BIGINT)
TO authenticated;

GRANT EXECUTE
ON FUNCTION public.get_id_card_by_token(UUID)
TO anon, authenticated;

-- ------------------------------------------------------------
-- Backfill tokens for existing records.
-- Existing tokens are preserved.
-- ------------------------------------------------------------
INSERT INTO public.id_card_tokens (
    school_id,
    entity_type,
    entity_id
)
SELECT
    s.school_id,
    'student',
    s.id
FROM public.students s
WHERE s.school_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM public.id_card_tokens ict
      WHERE ict.entity_type = 'student'
        AND ict.entity_id = s.id
  );

INSERT INTO public.id_card_tokens (
    school_id,
    entity_type,
    entity_id
)
SELECT
    t.school_id,
    'teacher',
    t.id
FROM public.teachers t
WHERE t.school_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM public.id_card_tokens ict
      WHERE ict.entity_type = 'teacher'
        AND ict.entity_id = t.id
  );

SELECT
    entity_type,
    COUNT(*) AS token_count
FROM public.id_card_tokens
GROUP BY entity_type
ORDER BY entity_type;
