-- ============================================================
-- SRMS PROMOTION MODULE
-- Manual administrator decision with automatic recommendation.
-- Rules:
--   * Average > 35%  -> automatic Promote recommendation.
--   * Average <= 35% -> Manual decision required.
--   * Missing results do NOT block promotion.
--   * Any unpublished result for the selected class/session blocks
--     the entire promotion batch until it is published.
--   * Existing results are never changed or deleted.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.student_enrolments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    session_id BIGINT NOT NULL REFERENCES public.academic_sessions(id) ON DELETE CASCADE,
    class_id BIGINT REFERENCES public.classes(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'completed', 'promoted', 'repeated', 'held')),
    promotion_batch_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (student_id, session_id)
);

CREATE INDEX IF NOT EXISTS idx_student_enrolments_school_session
    ON public.student_enrolments(school_id, session_id);
CREATE INDEX IF NOT EXISTS idx_student_enrolments_student
    ON public.student_enrolments(student_id);

CREATE TABLE IF NOT EXISTS public.promotion_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
    source_session_id BIGINT NOT NULL REFERENCES public.academic_sessions(id),
    destination_session_id BIGINT NOT NULL REFERENCES public.academic_sessions(id),
    source_class_id BIGINT NOT NULL REFERENCES public.classes(id),
    destination_class_id BIGINT REFERENCES public.classes(id),
    created_by UUID NOT NULL REFERENCES public.profiles(id),
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'completed', 'cancelled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_promotion_batches_school
    ON public.promotion_batches(school_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.promotion_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES public.promotion_batches(id) ON DELETE CASCADE,
    school_id BIGINT NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    source_class_id BIGINT NOT NULL REFERENCES public.classes(id),
    destination_class_id BIGINT REFERENCES public.classes(id),
    average_score NUMERIC(8,2),
    recommendation TEXT NOT NULL
        CHECK (recommendation IN ('auto_promote', 'manual_review', 'no_published_results')),
    decision TEXT NOT NULL
        CHECK (decision IN ('promote', 'repeat', 'hold')),
    reason TEXT,
    decided_by UUID NOT NULL REFERENCES public.profiles(id),
    decided_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (batch_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_promotion_decisions_batch
    ON public.promotion_decisions(batch_id);

ALTER TABLE public.student_enrolments
    DROP CONSTRAINT IF EXISTS student_enrolments_promotion_batch_fkey;
ALTER TABLE public.student_enrolments
    ADD CONSTRAINT student_enrolments_promotion_batch_fkey
    FOREIGN KEY (promotion_batch_id) REFERENCES public.promotion_batches(id) ON DELETE SET NULL;

ALTER TABLE public.student_enrolments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_decisions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view their school's enrolments" ON public.student_enrolments;
CREATE POLICY "Admins can view their school's enrolments"
ON public.student_enrolments FOR SELECT TO authenticated
USING (
    school_id IN (
        SELECT p.school_id FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role = 'admin'
    )
);

DROP POLICY IF EXISTS "Admins can view their school's promotion batches" ON public.promotion_batches;
CREATE POLICY "Admins can view their school's promotion batches"
ON public.promotion_batches FOR SELECT TO authenticated
USING (
    school_id IN (
        SELECT p.school_id FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role = 'admin'
    )
);

DROP POLICY IF EXISTS "Admins can view their school's promotion decisions" ON public.promotion_decisions;
CREATE POLICY "Admins can view their school's promotion decisions"
ON public.promotion_decisions FOR SELECT TO authenticated
USING (
    school_id IN (
        SELECT p.school_id FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role = 'admin'
    )
);

-- ------------------------------------------------------------
-- Promotion execution RPC.
-- The browser supplies final administrator decisions; the database
-- performs all writes in one transaction and validates school access.
-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS public.execute_promotion_batch(BIGINT, BIGINT, BIGINT, BIGINT, JSONB);

CREATE OR REPLACE FUNCTION public.execute_promotion_batch(
    p_source_session_id BIGINT,
    p_destination_session_id BIGINT,
    p_source_class_id BIGINT,
    p_destination_class_id BIGINT,
    p_decisions JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_school_id BIGINT;
    v_batch_id BIGINT;
    v_student RECORD;
    v_item JSONB;
    v_decision TEXT;
    v_destination BIGINT;
    v_average NUMERIC(8,2);
    v_recommendation TEXT;
    v_source_session_term TEXT;
    v_unpublished_count INTEGER;
    v_student_count INTEGER;
    v_decision_count INTEGER;
BEGIN
    SELECT p.school_id INTO v_school_id
    FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role = 'admin'
    LIMIT 1;

    IF v_school_id IS NULL THEN
        RAISE EXCEPTION 'Only a school administrator can execute promotion';
    END IF;

    IF p_source_session_id = p_destination_session_id THEN
        RAISE EXCEPTION 'Source and destination sessions must be different';
    END IF;

    IF p_decisions IS NULL OR jsonb_typeof(p_decisions) <> 'array' THEN
        RAISE EXCEPTION 'Promotion decisions must be a JSON array';
    END IF;

    SELECT term INTO v_source_session_term
    FROM public.academic_sessions
    WHERE id = p_source_session_id AND school_id = v_school_id;
    IF v_source_session_term IS NULL THEN
        RAISE EXCEPTION 'Source academic session not found in your school';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.academic_sessions
        WHERE id = p_destination_session_id AND school_id = v_school_id
    ) THEN
        RAISE EXCEPTION 'Destination academic session not found in your school';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.classes
        WHERE id = p_source_class_id AND school_id = v_school_id
    ) THEN
        RAISE EXCEPTION 'Source class not found in your school';
    END IF;

    IF p_destination_class_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.classes
        WHERE id = p_destination_class_id AND school_id = v_school_id
    ) THEN
        RAISE EXCEPTION 'Destination class not found in your school';
    END IF;

    -- Only existing result records matter here. Missing results are not a blocker.
    SELECT COUNT(*) INTO v_unpublished_count
    FROM public.results r
    JOIN public.students s ON s.id = r.student_id
    WHERE r.school_id = v_school_id
      AND r.session_id = p_source_session_id
      AND s.school_id = v_school_id
      AND s.class_id = p_source_class_id
      AND r.status <> 'published';

    IF v_unpublished_count > 0 THEN
        RAISE EXCEPTION 'Promotion blocked: % unpublished result record(s) remain for this class.', v_unpublished_count;
    END IF;

    SELECT COUNT(*) INTO v_student_count
    FROM public.students s
    WHERE s.school_id = v_school_id AND s.class_id = p_source_class_id;

    IF v_student_count = 0 THEN
        RAISE EXCEPTION 'There are no students in the selected source class';
    END IF;

    SELECT COUNT(*) INTO v_decision_count
    FROM jsonb_array_elements(p_decisions);

    IF v_decision_count <> v_student_count THEN
        RAISE EXCEPTION 'Promotion list is incomplete. Expected % student decisions but received %.', v_student_count, v_decision_count;
    END IF;

    -- Make sure every current student in the class has exactly one decision.
    IF EXISTS (
        SELECT 1
        FROM public.students s
        WHERE s.school_id = v_school_id
          AND s.class_id = p_source_class_id
          AND NOT EXISTS (
              SELECT 1 FROM jsonb_array_elements(p_decisions) d
              WHERE (d->>'student_id')::BIGINT = s.id
          )
    ) THEN
        RAISE EXCEPTION 'Promotion list does not contain every student in the selected class';
    END IF;

    INSERT INTO public.promotion_batches (
        school_id, source_session_id, destination_session_id,
        source_class_id, destination_class_id, created_by, status
    ) VALUES (
        v_school_id, p_source_session_id, p_destination_session_id,
        p_source_class_id, p_destination_class_id, auth.uid(), 'completed'
    ) RETURNING id INTO v_batch_id;

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_decisions)
    LOOP
        SELECT s.id, s.name, s.class_id INTO v_student
        FROM public.students s
        WHERE s.id = (v_item->>'student_id')::BIGINT
          AND s.school_id = v_school_id
          AND s.class_id = p_source_class_id;

        IF v_student.id IS NULL THEN
            RAISE EXCEPTION 'A promotion decision references a student outside the selected class';
        END IF;

        v_decision := lower(COALESCE(v_item->>'decision', ''));
        IF v_decision NOT IN ('promote', 'repeat', 'hold') THEN
            RAISE EXCEPTION 'Invalid promotion decision for student %', v_student.name;
        END IF;

        SELECT ROUND(AVG(r.total_score)::NUMERIC, 2)
        INTO v_average
        FROM public.results r
        WHERE r.school_id = v_school_id
          AND r.session_id = p_source_session_id
          AND r.student_id = v_student.id
          AND r.status = 'published';

        v_recommendation := CASE
            WHEN v_average IS NULL THEN 'no_published_results'
            WHEN v_average > 35 THEN 'auto_promote'
            ELSE 'manual_review'
        END;

        v_destination := CASE
            WHEN v_decision = 'promote' THEN COALESCE((v_item->>'destination_class_id')::BIGINT, p_destination_class_id)
            ELSE p_source_class_id
        END;

        IF v_decision = 'promote' AND v_destination IS NULL THEN
            RAISE EXCEPTION 'A destination class is required for promoted student %', v_student.name;
        END IF;

        IF v_destination IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM public.classes c
            WHERE c.id = v_destination AND c.school_id = v_school_id
        ) THEN
            RAISE EXCEPTION 'Invalid destination class for student %', v_student.name;
        END IF;

        INSERT INTO public.promotion_decisions (
            batch_id, school_id, student_id, source_class_id,
            destination_class_id, average_score, recommendation,
            decision, reason, decided_by
        ) VALUES (
            v_batch_id, v_school_id, v_student.id, p_source_class_id,
            v_destination, v_average, v_recommendation,
            v_decision, NULLIF(v_item->>'reason', ''), auth.uid()
        );

        -- Preserve the source class for this academic session.
        INSERT INTO public.student_enrolments (
            school_id, student_id, session_id, class_id, status, promotion_batch_id
        ) VALUES (
            v_school_id, v_student.id, p_source_session_id, p_source_class_id,
            CASE WHEN v_decision = 'repeat' THEN 'repeated' ELSE 'completed' END,
            v_batch_id
        )
        ON CONFLICT (student_id, session_id) DO UPDATE
        SET class_id = EXCLUDED.class_id,
            status = EXCLUDED.status,
            promotion_batch_id = EXCLUDED.promotion_batch_id;

        -- Record destination placement for the next academic session.
        INSERT INTO public.student_enrolments (
            school_id, student_id, session_id, class_id, status, promotion_batch_id
        ) VALUES (
            v_school_id, v_student.id, p_destination_session_id, v_destination,
            CASE WHEN v_decision = 'promote' THEN 'promoted'
                 WHEN v_decision = 'repeat' THEN 'repeated'
                 ELSE 'held' END,
            v_batch_id
        )
        ON CONFLICT (student_id, session_id) DO UPDATE
        SET class_id = EXCLUDED.class_id,
            status = EXCLUDED.status,
            promotion_batch_id = EXCLUDED.promotion_batch_id;

        -- students.class_id remains the current placement used by the existing SRMS.
        UPDATE public.students
        SET class_id = v_destination
        WHERE id = v_student.id AND school_id = v_school_id;
    END LOOP;

    RETURN v_batch_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.execute_promotion_batch(BIGINT, BIGINT, BIGINT, BIGINT, JSONB)
TO authenticated;
REVOKE EXECUTE ON FUNCTION public.execute_promotion_batch(BIGINT, BIGINT, BIGINT, BIGINT, JSONB)
FROM PUBLIC;
