-- ============================================================
-- S.A. KIDDIES ACADEMY SRMS
-- TIMETABLE MODULE
--
-- Uses the existing teachers / teacher_classes / teacher_subjects
-- catalog. This module stores only the actual timetable placement.
--
-- Rules enforced by the database:
--   1. A class cannot have two lessons in the same period.
--   2. A teacher cannot teach two classes in the same period.
--   3. Timetable entries belong to one academic session.
--   4. Existing teacher/class/subject records remain authoritative.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.timetable_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
    day_of_week TEXT NOT NULL CHECK (day_of_week IN ('Monday','Tuesday','Wednesday','Thursday','Friday')),
    period_no INTEGER NOT NULL CHECK (period_no > 0),
    label TEXT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_break BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (school_id, day_of_week, period_no)
);

CREATE TABLE IF NOT EXISTS public.timetable_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
    session_id BIGINT NOT NULL REFERENCES public.academic_sessions(id) ON DELETE CASCADE,
    class_id BIGINT NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
    subject_id BIGINT NOT NULL REFERENCES public.subjects(id) ON DELETE CASCADE,
    teacher_id BIGINT NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
    day_of_week TEXT NOT NULL CHECK (day_of_week IN ('Monday','Tuesday','Wednesday','Thursday','Friday')),
    period_no INTEGER NOT NULL CHECK (period_no > 0),
    room TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (school_id, session_id, class_id, day_of_week, period_no),
    UNIQUE (school_id, session_id, teacher_id, day_of_week, period_no)
);

CREATE INDEX IF NOT EXISTS idx_timetable_entries_school_session
    ON public.timetable_entries(school_id, session_id);
CREATE INDEX IF NOT EXISTS idx_timetable_entries_class
    ON public.timetable_entries(class_id, session_id);
CREATE INDEX IF NOT EXISTS idx_timetable_entries_teacher
    ON public.timetable_entries(teacher_id, session_id);

ALTER TABLE public.timetable_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timetable_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage timetable periods" ON public.timetable_periods;
CREATE POLICY "Admins manage timetable periods"
ON public.timetable_periods
FOR ALL TO authenticated
USING (
    school_id IN (
        SELECT p.school_id FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role = 'admin'
    )
)
WITH CHECK (
    school_id IN (
        SELECT p.school_id FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role = 'admin'
    )
);

DROP POLICY IF EXISTS "School users view timetable periods" ON public.timetable_periods;
CREATE POLICY "School users view timetable periods"
ON public.timetable_periods
FOR SELECT TO authenticated
USING (
    school_id IN (
        SELECT p.school_id FROM public.profiles p
        WHERE p.id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Admins manage timetable entries" ON public.timetable_entries;
CREATE POLICY "Admins manage timetable entries"
ON public.timetable_entries
FOR ALL TO authenticated
USING (
    school_id IN (
        SELECT p.school_id FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role = 'admin'
    )
)
WITH CHECK (
    school_id IN (
        SELECT p.school_id FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role = 'admin'
    )
);

DROP POLICY IF EXISTS "School users view timetable entries" ON public.timetable_entries;
CREATE POLICY "School users view timetable entries"
ON public.timetable_entries
FOR SELECT TO authenticated
USING (
    school_id IN (
        SELECT p.school_id FROM public.profiles p
        WHERE p.id = auth.uid()
    )
);

-- Keep updated_at current without introducing a new global trigger.
CREATE OR REPLACE FUNCTION public.touch_timetable_entry_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_timetable_entry_updated_at
ON public.timetable_entries;

CREATE TRIGGER trg_touch_timetable_entry_updated_at
BEFORE UPDATE ON public.timetable_entries
FOR EACH ROW
EXECUTE FUNCTION public.touch_timetable_entry_updated_at();

-- ------------------------------------------------------------
-- Standard S.A. Kiddies Academy periods currently used by the
-- timetable project.
-- Mon-Thu: 8:20am-1:50pm with break after period 4.
-- Friday: 8:20am-10:20am in 30-minute periods.
-- ------------------------------------------------------------

DO $$
DECLARE
    v_school_id BIGINT;
BEGIN
    FOR v_school_id IN SELECT id FROM public.schools LOOP
        INSERT INTO public.timetable_periods
            (school_id, day_of_week, period_no, label, start_time, end_time, is_break)
        VALUES
            (v_school_id, 'Monday',    1, 'P1', '08:20', '09:00', FALSE),
            (v_school_id, 'Monday',    2, 'P2', '09:00', '09:40', FALSE),
            (v_school_id, 'Monday',    3, 'P3', '09:40', '10:20', FALSE),
            (v_school_id, 'Monday',    4, 'P4', '10:20', '11:00', FALSE),
            (v_school_id, 'Monday',    5, 'P5', '11:30', '12:05', FALSE),
            (v_school_id, 'Monday',    6, 'P6', '12:05', '12:40', FALSE),
            (v_school_id, 'Monday',    7, 'P7', '12:40', '13:15', FALSE),
            (v_school_id, 'Monday',    8, 'P8', '13:15', '13:50', FALSE),
            (v_school_id, 'Tuesday',   1, 'P1', '08:20', '09:00', FALSE),
            (v_school_id, 'Tuesday',   2, 'P2', '09:00', '09:40', FALSE),
            (v_school_id, 'Tuesday',   3, 'P3', '09:40', '10:20', FALSE),
            (v_school_id, 'Tuesday',   4, 'P4', '10:20', '11:00', FALSE),
            (v_school_id, 'Tuesday',   5, 'P5', '11:30', '12:05', FALSE),
            (v_school_id, 'Tuesday',   6, 'P6', '12:05', '12:40', FALSE),
            (v_school_id, 'Tuesday',   7, 'P7', '12:40', '13:15', FALSE),
            (v_school_id, 'Tuesday',   8, 'P8', '13:15', '13:50', FALSE),
            (v_school_id, 'Wednesday', 1, 'P1', '08:20', '09:00', FALSE),
            (v_school_id, 'Wednesday', 2, 'P2', '09:00', '09:40', FALSE),
            (v_school_id, 'Wednesday', 3, 'P3', '09:40', '10:20', FALSE),
            (v_school_id, 'Wednesday', 4, 'P4', '10:20', '11:00', FALSE),
            (v_school_id, 'Wednesday', 5, 'P5', '11:30', '12:05', FALSE),
            (v_school_id, 'Wednesday', 6, 'P6', '12:05', '12:40', FALSE),
            (v_school_id, 'Wednesday', 7, 'P7', '12:40', '13:15', FALSE),
            (v_school_id, 'Wednesday', 8, 'P8', '13:15', '13:50', FALSE),
            (v_school_id, 'Thursday',  1, 'P1', '08:20', '09:00', FALSE),
            (v_school_id, 'Thursday',  2, 'P2', '09:00', '09:40', FALSE),
            (v_school_id, 'Thursday',  3, 'P3', '09:40', '10:20', FALSE),
            (v_school_id, 'Thursday',  4, 'P4', '10:20', '11:00', FALSE),
            (v_school_id, 'Thursday',  5, 'P5', '11:30', '12:05', FALSE),
            (v_school_id, 'Thursday',  6, 'P6', '12:05', '12:40', FALSE),
            (v_school_id, 'Thursday',  7, 'P7', '12:40', '13:15', FALSE),
            (v_school_id, 'Thursday',  8, 'P8', '13:15', '13:50', FALSE),
            (v_school_id, 'Friday',    1, 'P1', '08:20', '08:50', FALSE),
            (v_school_id, 'Friday',    2, 'P2', '08:50', '09:20', FALSE),
            (v_school_id, 'Friday',    3, 'P3', '09:20', '09:50', FALSE),
            (v_school_id, 'Friday',    4, 'P4', '09:50', '10:20', FALSE)
        ON CONFLICT (school_id, day_of_week, period_no) DO NOTHING;
    END LOOP;
END $$;

-- ------------------------------------------------------------
-- Database-level validation: a timetable row may only use records
-- belonging to the same school, and the teacher must already be
-- assigned to both the selected class and subject.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.validate_timetable_entry()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.academic_sessions WHERE id = NEW.session_id AND school_id = NEW.school_id) THEN
        RAISE EXCEPTION 'Academic session does not belong to this school';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.classes WHERE id = NEW.class_id AND school_id = NEW.school_id) THEN
        RAISE EXCEPTION 'Class does not belong to this school';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.subjects WHERE id = NEW.subject_id AND school_id = NEW.school_id) THEN
        RAISE EXCEPTION 'Subject does not belong to this school';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.teachers WHERE id = NEW.teacher_id AND school_id = NEW.school_id) THEN
        RAISE EXCEPTION 'Teacher does not belong to this school';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.teacher_classes
        WHERE teacher_id = NEW.teacher_id AND class_id = NEW.class_id
    ) THEN
        RAISE EXCEPTION 'Teacher is not assigned to the selected class in the Teacher Catalog';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.teacher_subjects
        WHERE teacher_id = NEW.teacher_id AND subject_id = NEW.subject_id
    ) THEN
        RAISE EXCEPTION 'Teacher is not assigned to the selected subject in the Teacher Catalog';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_timetable_entry
ON public.timetable_entries;

CREATE TRIGGER trg_validate_timetable_entry
BEFORE INSERT OR UPDATE ON public.timetable_entries
FOR EACH ROW
EXECUTE FUNCTION public.validate_timetable_entry();

-- ------------------------------------------------------------
-- Atomic save for the Auto Planner.
-- The whole generated timetable is inserted as one transaction.
-- If one row fails, none of the generated rows are saved.
-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS public.save_timetable_batch(BIGINT, BIGINT, JSONB);

CREATE OR REPLACE FUNCTION public.save_timetable_batch(
    p_school_id BIGINT,
    p_session_id BIGINT,
    p_entries JSONB
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_profile_school_id BIGINT;
    v_count INTEGER := 0;
    v_item JSONB;
BEGIN
    SELECT p.school_id
      INTO v_profile_school_id
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.role = 'admin'
    LIMIT 1;

    IF v_profile_school_id IS NULL OR v_profile_school_id <> p_school_id THEN
        RAISE EXCEPTION 'Only a school administrator can save an automatic timetable';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.academic_sessions
        WHERE id = p_session_id
          AND school_id = p_school_id
    ) THEN
        RAISE EXCEPTION 'Academic session does not belong to this school';
    END IF;

    IF p_entries IS NULL OR jsonb_typeof(p_entries) <> 'array' THEN
        RAISE EXCEPTION 'Timetable entries must be a JSON array';
    END IF;

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_entries)
    LOOP
        INSERT INTO public.timetable_entries (
            school_id,
            session_id,
            class_id,
            subject_id,
            teacher_id,
            day_of_week,
            period_no,
            room
        )
        VALUES (
            p_school_id,
            p_session_id,
            (v_item->>'class_id')::BIGINT,
            (v_item->>'subject_id')::BIGINT,
            (v_item->>'teacher_id')::BIGINT,
            v_item->>'day_of_week',
            (v_item->>'period_no')::INTEGER,
            NULLIF(v_item->>'room', '')
        );

        v_count := v_count + 1;
    END LOOP;

    RETURN v_count;
END;
$$;

GRANT EXECUTE ON FUNCTION public.save_timetable_batch(BIGINT, BIGINT, JSONB)
TO authenticated;

REVOKE EXECUTE ON FUNCTION public.save_timetable_batch(BIGINT, BIGINT, JSONB)
FROM PUBLIC;
